
export const GET_USER_RESERVATIONS = 'GET_USER_RESERVATIONS';

export const SET_RESERVATION = 'SET_RESERVATION';

export const ACCEPT_RESERVATION = 'ACCEPT_RESERVATION';

export const REJECT_RESERVATION = 'REJECT_RESERVATION';